on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'
      - name: Contributor_Submodules_Action
        uses: noahreinalter/Contributor_Submodules_Action@v2
        with:
          relink_submodules: 'true'
          update_submodules: 'true'
      - run: |
          git add .
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git diff-index --quiet HEAD || (git commit -m "Updated contributors" && git push)